"""Speech-to-Phrase custom sentence aggregation and export."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

GENERATED_HEADER = (
    "# Generated by Alice. Do not edit manually.\n"
    "# Rebuild with homeassistant service alice.rebuild_custom_sentences\n"
)


@dataclass
class SentenceConflict:
    """A detected conflict while aggregating custom sentences."""

    kind: str
    message: str
    details: dict[str, Any] = field(default_factory=dict)


@dataclass
class SentenceExportResult:
    """Result of exporting consolidated custom sentences."""

    language: str
    output_path: Path | None
    source_files: list[str]
    conflicts: list[SentenceConflict]
    intents: dict[str, Any] = field(default_factory=dict)


def load_sentence_file(path: Path) -> dict[str, Any]:
    """Load a Speech-to-Phrase sentence YAML file."""
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        msg = f"Invalid sentence file format in {path}"
        raise ValueError(msg)
    return data


def _iter_sentence_entries(intents: dict[str, Any]) -> list[tuple[str, dict[str, Any], str]]:
    entries: list[tuple[str, dict[str, Any], str]] = []
    for intent_name, intent_data in intents.items():
        for block in intent_data.get("data", []):
            for sentence in block.get("sentences", []):
                entries.append((intent_name, block, sentence))
    return entries


def _merge_data_blocks(existing: list[dict[str, Any]], incoming: list[dict[str, Any]]) -> list[dict[str, Any]]:
    merged_blocks = [dict(block) for block in existing]
    for block in incoming:
        sentences = list(block.get("sentences", []))
        if not sentences:
            merged_blocks.append(dict(block))
            continue

        slots = block.get("slots")
        match_index = None
        for index, existing_block in enumerate(merged_blocks):
            if existing_block.get("slots") == slots:
                match_index = index
                break

        if match_index is None:
            merged_blocks.append(dict(block))
            continue

        existing_sentences = list(merged_blocks[match_index].get("sentences", []))
        for sentence in sentences:
            if sentence not in existing_sentences:
                existing_sentences.append(sentence)
        merged_blocks[match_index]["sentences"] = existing_sentences

    return merged_blocks


def merge_sentence_data(
    sources: list[tuple[str, dict[str, Any]]],
) -> tuple[dict[str, Any], list[SentenceConflict]]:
    """Merge sentence YAML dictionaries from multiple sources."""
    language = next((data.get("language") for _, data in sources if data.get("language")), "en")
    merged_intents: dict[str, Any] = {}
    conflicts: list[SentenceConflict] = []
    sentence_owners: dict[str, set[str]] = {}

    for source_label, data in sources:
        intents = data.get("intents", {})
        for intent_name, intent_data in intents.items():
            if intent_name not in merged_intents:
                merged_intents[intent_name] = {"data": []}

            merged_intents[intent_name]["data"] = _merge_data_blocks(
                merged_intents[intent_name].get("data", []),
                intent_data.get("data", []),
            )

            for sentence in _iter_sentence_entries({intent_name: intent_data}):
                _, _, sentence_text = sentence
                owners = sentence_owners.setdefault(sentence_text, set())
                owners.add(f"{source_label}:{intent_name}")

    for sentence_text, owners in sorted(sentence_owners.items()):
        intent_names = {owner.split(":", 1)[1] for owner in owners}
        if len(intent_names) > 1:
            conflicts.append(
                SentenceConflict(
                    kind="duplicate_sentence",
                    message=f"Sentence '{sentence_text}' is used by multiple intents: {sorted(intent_names)}",
                    details={
                        "sentence": sentence_text,
                        "intents": sorted(intent_names),
                        "sources": sorted(owners),
                    },
                )
            )

    return {"language": language, "intents": merged_intents}, conflicts


def render_merged_yaml(language: str, intents: dict[str, Any]) -> str:
    """Render merged sentence data as YAML for Speech-to-Phrase."""
    payload = {"language": language, "intents": intents}
    body = yaml.safe_dump(payload, allow_unicode=True, sort_keys=False)
    return f"{GENERATED_HEADER}{body}"


def export_custom_sentences(
    output_dir: Path,
    language: str,
    source_paths: list[tuple[str, Path]],
) -> SentenceExportResult:
    """Aggregate source sentence files and write consolidated custom sentences."""
    loaded_sources: list[tuple[str, dict[str, Any]]] = []
    source_files: list[str] = []

    for label, path in source_paths:
        if not path.exists():
            continue
        loaded_sources.append((label, load_sentence_file(path)))
        source_files.append(str(path))

    if not loaded_sources:
        return SentenceExportResult(
            language=language,
            output_path=None,
            source_files=[],
            conflicts=[],
        )

    merged, conflicts = merge_sentence_data(loaded_sources)
    merged["language"] = language
    output_path = output_dir / language / "alice.yaml"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_merged_yaml(language, merged["intents"]),
        encoding="utf-8",
    )

    return SentenceExportResult(
        language=language,
        output_path=output_path,
        source_files=source_files,
        conflicts=conflicts,
        intents=merged["intents"],
    )
