"""Tests for Speech-to-Phrase custom sentence aggregation and export."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]
ALICE = ROOT / "custom_components" / "alice"
CONTAINMENT = (
    ROOT
    / "Containment Alarm Skill"
    / "custom_components"
    / "alice_containment_alarm"
    / "sentences"
)


def _load_module(name: str, filename: str):
    path = ALICE / filename
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


sentence_export = _load_module("alice.sentence_export", "sentence_export.py")

SentenceConflict = sentence_export.SentenceConflict
export_custom_sentences = sentence_export.export_custom_sentences
load_sentence_file = sentence_export.load_sentence_file
merge_sentence_data = sentence_export.merge_sentence_data


BASE_DE = {
    "language": "de",
    "intents": {
        "AliceMoodQuery": {
            "data": [
                {
                    "sentences": [
                        "wie ist deine laune",
                        "hey alice wie ist deine laune",
                    ]
                }
            ]
        },
        "AliceSetPreferredName": {
            "data": [
                {
                    "sentences": ["nenn mich {name}", "alice nenn mich {name}"],
                    "slots": {"name": {"type": "text"}},
                }
            ]
        },
    },
}

EXTENSION_DE = {
    "language": "de",
    "intents": {
        "AliceEnableContainment": {
            "data": [
                {
                    "sentences": [
                        "aktiviere sperrmodus",
                        "hey alice aktiviere sperrmodus",
                    ]
                }
            ]
        }
    },
}

CONFLICT_B = {
    "language": "de",
    "intents": {
        "AliceOtherIntent": {
            "data": [{"sentences": ["wie ist deine laune"]}]
        }
    },
}


def _write_yaml(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(data, allow_unicode=True, sort_keys=False), encoding="utf-8")


def test_load_sentence_file_reads_yaml(tmp_path: Path):
  path = tmp_path / "de.yaml"
  _write_yaml(path, BASE_DE)
  loaded = load_sentence_file(path)
  assert loaded["language"] == "de"
  assert "AliceMoodQuery" in loaded["intents"]


def test_merge_sentence_data_combines_distinct_intents():
  merged, conflicts = merge_sentence_data(
      [
          ("base", BASE_DE),
          ("containment", EXTENSION_DE),
      ]
  )
  assert conflicts == []
  assert "AliceMoodQuery" in merged["intents"]
  assert "AliceEnableContainment" in merged["intents"]


def test_merge_sentence_data_deduplicates_sentences_for_same_intent():
  duplicate = {
      "language": "de",
      "intents": {
          "AliceMoodQuery": {
              "data": [{"sentences": ["wie ist deine laune", "alice wie ist deine laune"]}]
          }
      },
  }
  merged, conflicts = merge_sentence_data([("base", BASE_DE), ("pack", duplicate)])
  assert conflicts == []
  sentences = merged["intents"]["AliceMoodQuery"]["data"][0]["sentences"]
  assert sentences.count("wie ist deine laune") == 1


def test_merge_sentence_data_detects_duplicate_sentence_across_intents():
  _, conflicts = merge_sentence_data(
      [
          ("base", BASE_DE),
          ("other", CONFLICT_B),
      ]
  )
  assert len(conflicts) == 1
  assert conflicts[0].kind == "duplicate_sentence"
  assert "wie ist deine laune" in conflicts[0].message


def test_export_custom_sentences_writes_consolidated_file(tmp_path: Path):
  base = tmp_path / "base" / "sentences" / "de.yaml"
  extension = tmp_path / "extension" / "sentences" / "de.yaml"
  _write_yaml(base, BASE_DE)
  _write_yaml(extension, EXTENSION_DE)

  result = export_custom_sentences(
      output_dir=tmp_path / "custom_sentences",
      language="de",
      source_paths=[("base", base), ("containment", extension)],
  )

  assert result.output_path == tmp_path / "custom_sentences" / "de" / "alice.yaml"
  assert result.output_path.exists()
  assert result.conflicts == []
  assert len(result.source_files) == 2

  exported = yaml.safe_load(result.output_path.read_text(encoding="utf-8"))
  assert exported["language"] == "de"
  assert "AliceMoodQuery" in exported["intents"]
  assert "AliceEnableContainment" in exported["intents"]
  assert "Generated by Alice" in result.output_path.read_text(encoding="utf-8")


def test_export_custom_sentences_skips_missing_language_files(tmp_path: Path):
  missing = tmp_path / "extension" / "sentences" / "fr.yaml"
  base = tmp_path / "base" / "sentences" / "fr.yaml"
  _write_yaml(base, {"language": "fr", "intents": {"AliceMoodQuery": {"data": [{"sentences": ["quelle est ton humeur"]}]}}})

  result = export_custom_sentences(
      output_dir=tmp_path / "custom_sentences",
      language="fr",
      source_paths=[("base", base), ("missing", missing)],
  )

  assert result.output_path is not None
  assert result.output_path.exists()
  assert len(result.source_files) == 1


def test_base_integration_sentence_files_exist_and_load():
  base_de = ALICE / "sentences" / "de.yaml"
  base_en = ALICE / "sentences" / "en.yaml"
  assert base_de.exists()
  assert base_en.exists()

  de = load_sentence_file(base_de)
  en = load_sentence_file(base_en)
  assert "AliceMoodQuery" in de["intents"]
  assert "AliceMoodQuery" in en["intents"]


def test_export_includes_containment_extension_sentences(tmp_path: Path):
  containment_de = CONTAINMENT / "de.yaml"
  assert containment_de.exists()

  result = export_custom_sentences(
      output_dir=tmp_path / "custom_sentences",
      language="de",
      source_paths=[
          ("base", ALICE / "sentences" / "de.yaml"),
          ("alice_containment_alarm", containment_de),
      ],
  )

  exported = yaml.safe_load(result.output_path.read_text(encoding="utf-8"))
  assert "AliceEnableContainment" in exported["intents"]
  assert "aktiviere sperrmodus" in exported["intents"]["AliceEnableContainment"]["data"][0]["sentences"]
